---
apiVersion: v2
name: arma3
description: |
  A Helm chart for [Arma 3](https://arma3.com/).

  Requires:
    - an existing secret with credentials for Steam and the Server

  Optional:
    - [stakater/reloader](https://github.com/stakater/Reloader) to trigger pod updates on config changes
    - [metallb](https://github.com/metallb/metallb) when hosting on bare-metal
    - a CSI driver that supports ReadWriteMany volumes (or plain NFS)

  See [configuration](./docs/configuration.md) and [development](./docs/development.md) for more details.

  This project uses the following components:

    - [Arma3Server Docker Image](https://github.com/fbuchmeier/Arma3Server)
    - [rsync-server Docker Image](https://github.com/fbuchmeier/rsync-server)
    - [Debian Bullseye Docker Image](https://github.com/docker-library/repo-info/blob/master/repos/debian/remote/bullseye.md)
    - [Common Utils](https://github.com/fbuchmeier/utils-docker)

  Special thanks to:

    - [axiom-data-science](https://github.com/axiom-data-science) for their rsync-server docker image
    - [BrettMayson](https://github.com/BrettMayson) for his Arma 3 docker image

  Development:

    - [helm-docs](https://github.com/norwoodj/helm-docs)
    - [kubeconform](https://github.com/yannh/kubeconform)
    - [yamllint](https://github.com/adrienverge/yamllint)
    - [rewrap](https://stkb.github.io/Rewrap/)
    - [markdownlint](https://github.com/markdownlint/markdownlint)
    - [convco](https://convco.github.io/)
    - [yq](https://github.com/mikefarah/yq)
type: application
version: "0.5.5"
appVersion: "2.2.0"
maintainers:
  - name: Florian Buchmeier
    email: flo_buchmeier@web.de
    url: https://github.com/fbuchmeier
