apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "arma3.fullname" . }}
  labels:
    {{- include "arma3.labels" . | nindent 4 }}
  {{- with .Values.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  strategy:
    type: Recreate
  {{- if .Values.replicas }}
  replicas: 1
  {{- end }}
  selector:
    matchLabels:
      {{- include "arma3.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: server
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: "server"
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "arma3.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: server
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "arma3.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        {{- if (include "rsyncEnabled" .) }}
        - name: rsyncd
          securityContext:
            {{- toYaml .Values.rsync.securityContext | nindent 12 }}
          image: "{{ .Values.rsync.image.repository }}:{{ .Values.rsync.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.rsync.image.pullPolicy }}
          env:
            - name: USERNAME
              value: {{ .Values.headlessclient.name }}
            - name: PASSWORD
              value: {{ include "serverPassword" . }}
            - name: VOLUME
              value: /arma3
          ports:
            - containerPort: 8873
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 8873
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - cat /tmp/arma3_install_success
            initialDelaySeconds: 60
            periodSeconds: 20
          resources:
            {{- toYaml .Values.rsync.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /arma3
              readOnly: true
            - name: tmp
              mountPath: /tmp
              readOnly: false
            - name: rsyncd
              mountPath: /opt/rsyncd
              readOnly: false
        {{- end }}
      {{- if .Values.headlessclient.enabled }}
        - name: tunnel
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.tunnel.image.repository }}:{{ .Values.tunnel.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - containerPort: 3002
            protocol: UDP
          - containerPort: 3003
            protocol: UDP
          - containerPort: 3004
            protocol: UDP
          - containerPort: 3005
            protocol: UDP
          - containerPort: 3006
            protocol: UDP
          resources:
            {{- toYaml .Values.tunnel.resources | nindent 12 }}
          volumeMounts:
          - mountPath: /etc/envoy
            name: envoy-config
            readOnly: true
          {{- end }}
        - name: server
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "arma3.fullname" . }}-env
          ports:
            - containerPort: 2302
              protocol: UDP
            - containerPort: 2303
              protocol: UDP
            - containerPort: 2304
              protocol: UDP
            - containerPort: 2305
              protocol: UDP
            - containerPort: 2306
              protocol: UDP
            - name: metrics
              containerPort: 8000
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - cat /tmp/arma3_launch_success
            initialDelaySeconds: 60
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /arma3/configs/main.cfg
              subPath: main.cfg
              readOnly: true
            - name: data
              mountPath: /arma3
              readOnly: false
            - name: profile
              mountPath: /arma3/configs/profiles/home/main
              readOnly: false
            - name: modpresets
              mountPath: /modpresets
              readOnly: true
            - name: tmp
              mountPath: /tmp
              readOnly: false
            - name: home
              mountPath: /home/steam
              readOnly: false
            - name: steamcmd
              mountPath: /steamcmd
              readOnly: false
      volumes:
        - name: config
          configMap:
            name: {{ include "arma3.fullname" . }}
        - name: data
          {{- if .Values.persistence.data.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "arma3.fullname" . }}-data
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: profile
          {{- if .Values.persistence.profile.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "arma3.fullname" . }}-profile
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: modpresets
          configMap:
            name: {{ include "arma3.fullname" . }}-modpresets
        - name: scripts
          configMap:
            name: {{ include "arma3.fullname" . }}-scripts
        - name: tmp
          emptyDir:
            medium: Memory
        - name: rsyncd
          emptyDir:
            medium: Memory
        - name: home
          emptyDir: {}
        - name: steamcmd
          emptyDir: {}
        {{- if .Values.headlessclient.enabled }}
        - name: envoy-config
          configMap:
            defaultMode: 420
            name: {{ include "arma3.fullname" . }}-tunnel
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
