{
 "title": "ARMA3 - Antistasi",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(up{job=\"kube-state-metrics\"}, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\", cluster=\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_info{job=\"kube-state-metrics\", cluster=\"$cluster\", namespace=\"$namespace\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Faction Stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(arma3_antistasi_hr{pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{pod}} - HR"
    },
    {
     "expr": "sum(arma3_antistasi_faction_cash{pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{pod}} - Cash"
    }
   ]
  },
  {
   "title": "Aggro",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(arma3_antistasi_inv_aggro{pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{pod}} - Invader"
    },
    {
     "expr": "sum(arma3_antistasi_occ_aggro{pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{pod}} - Occupant"
    },
    {
     "expr": "sum(arma3_antistasi_warlevel{pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{pod}} - War Level"
    }
   ]
  },
  {
   "title": "Vehicles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(arma3_antistasi_all_vehicles{pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{pod}} - All Vehicles"
    },
    {
     "expr": "sum(arma3_antistasi_wrecked_vehicles{pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{pod}} - Wrecked Vehicles"
    }
   ]
  },
  {
   "title": "Units",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(arma3_antistasi_all_units{pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{pod}} - All Units"
    },
    {
     "expr": "sum(arma3_antistasi_dead_units{pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{pod}} - Dead Units"
    },
    {
     "expr": "sum(arma3_antistasi_units_aware_of_enemies{pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{pod}} - Units Aware of Enemies"
    }
   ]
  },
  {
   "title": "Groups",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(arma3_antistasi_groups_civ{pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{pod}} - Civ"
    },
    {
     "expr": "sum(arma3_antistasi_groups_combat_behaviour{pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{pod}} - Combat"
    },
    {
     "expr": "sum(arma3_antistasi_groups_invaders{pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{pod}} - Invaders"
    },
    {
     "expr": "sum(arma3_antistasi_groups_occupants{pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{pod}} - Occupants"
    },
    {
     "expr": "sum(arma3_antistasi_groups_rebels{pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{pod}} - Rebels"
    },
    {
     "expr": "sum(arma3_antistasi_groups_total{pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{pod}} - Total"
    }
   ]
  },
  {
   "title": "Server FPS and Players",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(arma3_antistasi_server_fps{pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{pod}} - Server FPS"
    },
    {
     "expr": "sum(arma3_antistasi_players{pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{pod}} - Players"
    }
   ]
  }
 ]
}